//! Typed identifier newtypes for the Ken protocol.
//!
//! Each identifier is a newtype around [`Uuid`] that prevents mix-ups
//! at the type level. An [`EndpointId`] cannot be passed where a
//! [`CommandId`] is expected, even though both are UUIDs internally.
//! See ADR-0001 for the trust boundaries these identifiers enforce.

use std::fmt;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Stable identifier for an enrolled endpoint, assigned by the server
/// at enrollment time.
///
/// Endpoints are enrolled manually by the family IT chief per
/// ADR-0001 T2-7. This type is the handle to a single enrolled agent
/// throughout the system.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EndpointId(Uuid);

impl EndpointId {
    /// Generate a fresh random endpoint identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Create an identifier from an existing UUID.
    #[must_use]
    pub fn from_uuid(id: Uuid) -> Self {
        Self(id)
    }

    /// Parse an identifier from its string representation.
    ///
    /// # Errors
    ///
    /// Returns an error if the string is not a valid UUID.
    pub fn parse(s: &str) -> Result<Self, uuid::Error> {
        Uuid::parse_str(s).map(Self)
    }

    /// Return the underlying UUID.
    #[must_use]
    pub fn as_uuid(&self) -> &Uuid {
        &self.0
    }
}

impl Default for EndpointId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for EndpointId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Unique identifier for a command sent from server to agent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CommandId(Uuid);

impl CommandId {
    /// Generate a fresh random command identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Create an identifier from an existing UUID.
    #[must_use]
    pub fn from_uuid(id: Uuid) -> Self {
        Self(id)
    }

    /// Parse an identifier from its string representation.
    ///
    /// # Errors
    ///
    /// Returns an error if the string is not a valid UUID.
    pub fn parse(s: &str) -> Result<Self, uuid::Error> {
        Uuid::parse_str(s).map(Self)
    }

    /// Return the underlying UUID.
    #[must_use]
    pub fn as_uuid(&self) -> &Uuid {
        &self.0
    }
}

impl Default for CommandId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for CommandId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Unique identifier for a heartbeat, generated by the agent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct HeartbeatId(Uuid);

impl HeartbeatId {
    /// Generate a fresh random heartbeat identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Create an identifier from an existing UUID.
    #[must_use]
    pub fn from_uuid(id: Uuid) -> Self {
        Self(id)
    }

    /// Parse an identifier from its string representation.
    ///
    /// # Errors
    ///
    /// Returns an error if the string is not a valid UUID.
    pub fn parse(s: &str) -> Result<Self, uuid::Error> {
        Uuid::parse_str(s).map(Self)
    }

    /// Return the underlying UUID.
    #[must_use]
    pub fn as_uuid(&self) -> &Uuid {
        &self.0
    }
}

impl Default for HeartbeatId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for HeartbeatId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Identifier for a remote session, reserved for Phase 2.
///
/// Defined now to lock the type in the wire protocol so that adding
/// the `RustDesk`-based remote session subsystem in Phase 2 does not
/// require a schema version bump.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SessionId(Uuid);

impl SessionId {
    /// Generate a fresh random session identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Create an identifier from an existing UUID.
    #[must_use]
    pub fn from_uuid(id: Uuid) -> Self {
        Self(id)
    }

    /// Parse an identifier from its string representation.
    ///
    /// # Errors
    ///
    /// Returns an error if the string is not a valid UUID.
    pub fn parse(s: &str) -> Result<Self, uuid::Error> {
        Uuid::parse_str(s).map(Self)
    }

    /// Return the underlying UUID.
    #[must_use]
    pub fn as_uuid(&self) -> &Uuid {
        &self.0
    }
}

impl Default for SessionId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SessionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn endpoint_id_display_matches_uuid() {
        let uuid = Uuid::new_v4();
        let id = EndpointId::from_uuid(uuid);
        assert_eq!(id.to_string(), uuid.to_string());
    }

    #[test]
    fn command_id_display_matches_uuid() {
        let uuid = Uuid::new_v4();
        let id = CommandId::from_uuid(uuid);
        assert_eq!(id.to_string(), uuid.to_string());
    }

    #[test]
    fn heartbeat_id_display_matches_uuid() {
        let uuid = Uuid::new_v4();
        let id = HeartbeatId::from_uuid(uuid);
        assert_eq!(id.to_string(), uuid.to_string());
    }

    #[test]
    fn session_id_display_matches_uuid() {
        let uuid = Uuid::new_v4();
        let id = SessionId::from_uuid(uuid);
        assert_eq!(id.to_string(), uuid.to_string());
    }

    #[test]
    fn endpoint_id_parse_roundtrip() {
        let id = EndpointId::new();
        let parsed = EndpointId::parse(&id.to_string()).unwrap();
        assert_eq!(id, parsed);
    }

    #[test]
    fn different_id_types_are_not_interchangeable() {
        // This test exists to document the type-safety guarantee.
        // The compiler prevents passing a CommandId where an EndpointId
        // is expected — this test verifies the types are distinct at
        // the value level too.
        let uuid = Uuid::new_v4();
        let endpoint = EndpointId::from_uuid(uuid);
        let command = CommandId::from_uuid(uuid);
        // Same underlying UUID, but different types — cannot be compared.
        assert_eq!(endpoint.to_string(), command.to_string());
    }
}
